### ISSUE TITLE
EDA figures + code

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/global_warming_effects_on_ice_thickness#37]
Many figures are get cut between pages in the PDF document, which makes it hard to read. Also, it would be helpful to summarize all the EDA, and at least connect the main findings between each plot. There are many figures so this would be helpful.

**Comment by sbabicki** [comment]
Thanks @abaghela, agreed. The PDF was a last resort because the figures were too large to be previewed as .md file in GitHub D:

@syadk I think these issues will be addressed in the pared-down version you are creating based on what we discussed in the lab. Hopefully the smaller EDA document can be exported as a markdown file instead of a PDF.

**Comment by sbabicki** [comment]
@syadk also, based on this feedback I think you should replace the current EDA notebook with the updated one you create.

**Comment by syadk** [comment]
@sbabicki I created a .py script that saves the two figures we discussed as png's. I assumed that the 5th script (Mo) would produce the markdown/notebook with a small description of what the images are showing (which I'll provide him). Let me know if I've misunderstood what my script 3 should be doing
