### ISSUE TITLE
Paragraph describing script 4 analysis

### ISSUE THREAD

**Issue by jaymegordo** [UBC-MDS/global_warming_effects_on_ice_thickness#39]
@jaymegordo Can you also write a paragraph on what was done for the analysis that @mgaroub can include in the final report?

_Originally posted by @sbabicki in https://github.com/UBC-MDS/global_warming_effects_on_ice_thickness/issues/31#issuecomment-734510282_

**Comment by jaymegordo** [comment]
In this analysis, we compare the median ice thickness measurements per station for all years in the range (1984, 1996) for the month of January... (results/median_ice_thickness.png)

We then calculte the p-value of samples between 1984 and 1994 for each of January, February, and March... (results/p_values.csv)

**Comment by sbabicki** [comment]
In this analysis, we compare the median ice thickness measurements between [month] [year1] and [month] [year2] and conduct a hypothesis test to determine if the difference in medians is statistically significant. 

For our analysis we chose to use a hypothesis test for independence of a difference in medians using permutation. The permutation test assumes that all observations are independent, so we have adjusted our data in order to meet this condition. The ice thickness measurements are taken weekly, so we decided to take the mean of the ice thickness per station per month in order to compare with other years. With this methodology we satisfy the condition that the observations are from different individuals (stations). 

Our null hypothesis is that the median ice thickness in [year1] is the same as the median ice thickness in [year2]. Our alternative hypothesis is that the median ice thickness in [year1] is different than median ice thickness in [year2].
$H_0 = \text{median}_198X -  \text{median}_199X = 0$
$H_A = \text{median}_198X -  \text{median}_199X \neq 0$

For our hypothesis test we chose an $\alpha = 0.05$, however we would need to do further research to determine if this is the domain standard. 

We calculated that the difference between the sample medians of average ice thickness measurements by station for [month] [year1] and [month] [year2] and the corresponding 95% confidence intervals.

Using the permutation test we determined the p-values. Our p-values from our test of independence of a difference in medians using permutation  were < $\alpha$, so we fail to reject our null hypothesis,  $H_0$. Based on this evidence, it appears that there is no statistically significant difference between the median ice thickness ice thickness measurements of [month] [year1] and [month] [year2].
[TABLE - P-VALUE RESULTS]

In the next Milestone, we hope to explore additional months and years to see if we obtain the same result. As can be seen in the figure below, the years we have chosen have overlapping confidence intervals and the medians are not as disimilar as other combinations of months and years.
[FIGURE - CONFIDENCE INTERVALS]
