### ISSUE TITLE
Peer Feedback 

### ISSUE THREAD

**Issue by jkim222383** [UBC-MDS/global_warming_effects_on_ice_thickness#90]
Hello,

I enjoyed reading your report. Instructions in README are very clear, and I was able to run the scripts to reproduce the report without any issue at all.

Overall, the report (research question, methodology, analysis) is fairly clear and easy to follow. Some comments/suggestions I had:

- Regarding Makefile, some of the dependencies probably need to be moved around. For example, `data/processed/ice_thickness` would depend on `data/raw/ice_thickness.csv`. `results/median_thickness_year.svg` would depend on `data/processed/ice_thickness`, and so on.
After updating the dependencies for the intermediate files, Makefile rule for `all` would likely depend only on the final output files `doc/global_warming_effects_on_ice_thickness.md` and `doc/global_warming_effects_on_ice_thickness.html`

- Research question in Summary section seems to focus on change from 1984 to 1996, and EDA visualization appears to be comparing data between 1984 and 1996. The rest of the analysis starting from the null and alternate hypotheses appear to be comparing between years 1984 and 1994. This may need further explanation or may need updating either Summary & EDA or the rest of the report. (I realize after writing this that TA already pointed this out.) 

- EDA discusses examining whether the difference in median thickness is subject to certain month or whether the difference is present throughout all months, but only examines Jan – Mar. Although these plots are only meant as an exploratory data viz, it would be more helpful to look at months that are more spread out over all months instead of just the first three months (years 1984 and 1994/1996 have data from Jan – Jun and Oct - Dec). 

- Since the scope of analysis changed (comparing median ice thickness in Jan 1984 to median ice thickness in Jan 1994) instead of median in 1984 and median in 1994, the null/alternate hypotheses may need to be modified to reflect this change.

Please let me know if you have any questions/clarifications!

**Comment by aidanmattrick** [comment]
Hey all,

Here are my impressions from reviewing and building your project:

- Documentation:
  - Very clear and well laid out. Only comment I would have is that generated files (i.e. graphs) already exist in the repo so if one wants to build, they should run make clean first. This could be made a bit more clear.
- Code:
  - Readable and reproducible. Only one exception was that the `density.svg` plot didn't properly render.
- Analysis & Reasoning:
  - Thought you did a good job here. The only thing I was curious about that I would have liked to hear about is what your thoughts are with the outlier in the dataset of the year 2002. I know this is outside the scope of the question but since this data point was included I was curious for your interpretation.
  - Maybe consider putting this section in a separate `reports` directory instead of in `docs` but this might be more of a subjective criticism than an objective one. One additional thing I thought might be helpful (if possible) is a brief overview of the different stations involved in data collection (i.e. number and location).
- Communication:
  - Nothing really stood out to me as needing improvement here. Well written and easy to read/follow along with. Only thing I might suggest is adding some more information around seasonality piece. I am uncertain as to how seasonality is not taken into account given that data was collected at the same time each year.

**Comment by sbabicki** [comment]
Thanks very much for your detailed review, Junghoo!

**Comment by mgaroub** [comment]
Thanks Aidan and Junghoo!
